services:
  magic:
    container_name: mage-local
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/mage.dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
      MLFLOW_TRACKING_URI: http://mlflow-local:5000
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    depends_on:
      - mlflow
    networks:
      - ml-pipeline

  mlflow:
    container_name: mlflow-local
    build:
      context: .
      dockerfile: ./docker/mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data/"
    networks:
      - ml-pipeline

networks:
  ml-pipeline:
    driver: bridge
    name: ml-pipeline